import React, { useEffect, useState, useCallback, useMemo } from "react";
import { LayoutGrid, Table2 } from "lucide-react";
import api, { inr } from "@/lib/api";
import {
  PageHeader, StatCard, DataTable, StatusBadge, Card, EmptyState,
} from "@/components/enterprise";
import { useBrand } from "@/context/BrandContext";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";

const KANBAN_COLS = [
  { key: "lead", label: "Leads", color: "border-t-slate-400" },
  { key: "client", label: "Clients", color: "border-t-primary" },
];

export default function AdminLeads({ mode = "leads" }) {
  const { brands, locked, brandKey } = useBrand();
  const [partners, setPartners] = useState([]);
  const [items, setItems] = useState([]);
  const [partnerId, setPartnerId] = useState("all");
  const [brandFilter, setBrandFilter] = useState("all");
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState("table");
  const [selected, setSelected] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [pres, lres] = await Promise.all([
        api.get("/partners", { params: locked ? { brand: brandKey } : {} }),
        api.get("/leads", {
          params: {
            ...(partnerId !== "all" ? { partner_id: partnerId } : {}),
            ...(locked ? { brand: brandKey } : (brandFilter !== "all" ? { brand: brandFilter } : {})),
            ...(mode === "clients" || mode === "payments" ? { status: "client" } : {}),
          },
        }),
      ]);
      setPartners(pres.data);
      setItems(lres.data);
    } finally {
      setLoading(false);
    }
  }, [partnerId, brandFilter, mode, locked, brandKey]);

  useEffect(() => { load(); }, [load]);

  const totals = items.reduce((acc, l) => {
    acc.leads += 1;
    if (l.status === "client") acc.clients += 1;
    if (l.status === "client" && l.payment_status === "paid") acc.paid += l.deal_value;
    if (l.status === "client" && l.payment_status === "unpaid") acc.unpaid += l.deal_value;
    return acc;
  }, { leads: 0, clients: 0, paid: 0, unpaid: 0 });

  const titles = {
    leads: { eyebrow: "Lead Management", title: "All Leads", desc: "Every school lead generated by partners.", breadcrumb: "Leads" },
    clients: { eyebrow: "Client Management", title: "Converted Clients", desc: "Leads that crossed the line into clients.", breadcrumb: "Clients" },
    payments: { eyebrow: "Payments", title: "Payments Ledger", desc: "Payment value for every client.", breadcrumb: "Payments" },
  };
  const t = titles[mode];

  const columns = [
    {
      key: "school",
      header: "School",
      render: (l) => (
        <div>
          <p className="font-medium">{l.school_name}</p>
          <p className="text-xs text-muted-foreground truncate max-w-[200px]">{l.address}</p>
        </div>
      ),
    },
    {
      key: "partner",
      header: "Partner",
      render: (l) => (
        <div>
          <p className="text-sm">{l.partner_name}</p>
          <p className="text-xs text-muted-foreground">{brands[l.brand]?.name || l.brand}</p>
        </div>
      ),
    },
    { key: "target_title", header: "Target" },
    {
      key: "classes",
      header: "Classes",
      render: (l) => (
        <div className="flex flex-wrap gap-1">
          {(l.target_classes || []).slice(0, 4).map((c) => (
            <span key={c} className="text-[10px] px-1.5 py-0.5 rounded bg-muted font-mono-tabular">{c}</span>
          ))}
          {(l.target_classes || []).length > 4 && <span className="text-[10px] text-muted-foreground">+{l.target_classes.length - 4}</span>}
        </div>
      ),
    },
    {
      key: "deal_value",
      header: "Deal",
      className: "text-right",
      render: (l) => <span className="font-mono-tabular text-sm font-medium">{inr(l.deal_value)}</span>,
    },
    {
      key: "status",
      header: "Status",
      className: "text-right",
      render: (l) => (
        <div className="flex items-center justify-end gap-1.5">
          <StatusBadge status={l.status} />
          {l.status === "client" && <StatusBadge status={l.payment_status} />}
        </div>
      ),
    },
  ];

  const kanbanItems = useMemo(() => {
    const cols = { lead: [], client: [] };
    items.forEach((l) => cols[l.status === "client" ? "client" : "lead"].push(l));
    return cols;
  }, [items]);

  return (
    <div>
      <PageHeader
        title={t.title}
        description={t.desc}
        testid={`admin-${mode}-header`}
        breadcrumbs={[{ label: "Admin", to: "/admin" }, { label: t.breadcrumb }]}
        actions={
          mode === "leads" && (
            <div className="flex rounded-lg border border-border p-0.5 bg-muted/50">
              <button type="button" onClick={() => setView("table")} className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors", view === "table" ? "bg-card shadow-sm text-foreground" : "text-muted-foreground")}>
                <Table2 size={14} /> Table
              </button>
              <button type="button" onClick={() => setView("kanban")} className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors", view === "kanban" ? "bg-card shadow-sm text-foreground" : "text-muted-foreground")}>
                <LayoutGrid size={14} /> Kanban
              </button>
            </div>
          )
        }
      />

      <div className="p-6 lg:p-8 space-y-6">
        <Card padding="p-4">
          <div className={`grid grid-cols-1 ${locked ? "" : "md:grid-cols-2"} gap-4`}>
            <div>
              <Label className="text-xs text-muted-foreground">Partner</Label>
              <Select value={partnerId} onValueChange={setPartnerId}>
                <SelectTrigger className="rounded-lg h-10 mt-1.5" data-testid="filter-partner-select"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All partners</SelectItem>
                  {partners.map((p) => <SelectItem key={p.id} value={p.id}>{p.name} — {p.city}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            {!locked && (
              <div>
                <Label className="text-xs text-muted-foreground">Brand</Label>
                <Select value={brandFilter} onValueChange={setBrandFilter}>
                  <SelectTrigger className="rounded-lg h-10 mt-1.5" data-testid="filter-brand-leads-select"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All verticals</SelectItem>
                    {Object.values(brands).map((b) => <SelectItem key={b.key} value={b.key}>{b.name}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>
        </Card>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {mode === "payments" ? (
            <>
              <StatCard label="Clients" value={totals.clients} loading={loading} />
              <StatCard label="Paid Revenue" value={inr(totals.paid)} loading={loading} />
              <StatCard label="Pending" value={inr(totals.unpaid)} loading={loading} />
              <StatCard label="Total Value" value={inr(totals.paid + totals.unpaid)} loading={loading} />
            </>
          ) : (
            <>
              <StatCard label="Records" value={totals.leads} loading={loading} />
              <StatCard label="Clients" value={totals.clients} loading={loading} />
              <StatCard label="Paid" value={inr(totals.paid)} loading={loading} />
              <StatCard label="Pending" value={inr(totals.unpaid)} loading={loading} />
            </>
          )}
        </div>

        {view === "kanban" && mode === "leads" ? (
          <div className="grid md:grid-cols-2 gap-4">
            {KANBAN_COLS.map((col) => (
              <div key={col.key} className={cn("rounded-xl border border-border bg-card border-t-4", col.color)}>
                <div className="px-4 py-3 border-b border-border flex items-center justify-between">
                  <span className="text-sm font-semibold">{col.label}</span>
                  <span className="text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded-full">{kanbanItems[col.key].length}</span>
                </div>
                <div className="p-3 space-y-2 max-h-[500px] overflow-y-auto">
                  {loading ? (
                    <p className="text-sm text-muted-foreground p-4 text-center">Loading…</p>
                  ) : kanbanItems[col.key].length === 0 ? (
                    <EmptyState title={`No ${col.label.toLowerCase()}`} />
                  ) : (
                    kanbanItems[col.key].map((l) => (
                      <button
                        key={l.id}
                        type="button"
                        onClick={() => setSelected(l)}
                        data-testid={`lead-row-${l.id}`}
                        className="w-full text-left p-3 rounded-lg border border-border/60 bg-background hover:shadow-sm hover:border-border transition-all"
                      >
                        <p className="text-sm font-medium">{l.school_name}</p>
                        <p className="text-xs text-muted-foreground mt-1">{l.partner_name} · {inr(l.deal_value)}</p>
                      </button>
                    ))
                  )}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <DataTable
            columns={columns}
            data={items.map((l) => ({ ...l, testid: `lead-row-${l.id}` }))}
            loading={loading}
            emptyTitle="No records yet"
            onRowClick={setSelected}
          />
        )}
      </div>

      <Sheet open={!!selected} onOpenChange={() => setSelected(null)}>
        <SheetContent className="w-full sm:max-w-md">
          {selected && (
            <>
              <SheetHeader>
                <SheetTitle>{selected.school_name}</SheetTitle>
                <SheetDescription>{selected.address}</SheetDescription>
              </SheetHeader>
              <div className="mt-6 space-y-4">
                <div className="flex gap-2">
                  <StatusBadge status={selected.status} />
                  {selected.status === "client" && <StatusBadge status={selected.payment_status} />}
                </div>
                <div className="space-y-3">
                  {[
                    ["Partner", selected.partner_name],
                    ["Target", selected.target_title],
                    ["Deal Value", inr(selected.deal_value)],
                    ["Classes", (selected.target_classes || []).join(", ")],
                    ["Description", selected.description || "—"],
                  ].map(([label, val]) => (
                    <div key={label} className="p-3 rounded-lg bg-muted/40">
                      <p className="text-[10px] uppercase text-muted-foreground font-medium">{label}</p>
                      <p className="text-sm mt-0.5">{val}</p>
                    </div>
                  ))}
                </div>
                <div className="border-l-2 border-primary/30 pl-4 space-y-3">
                  <p className="text-xs font-semibold text-muted-foreground uppercase">Timeline</p>
                  <div className="text-sm">
                    <p className="font-medium">Lead created</p>
                    <p className="text-xs text-muted-foreground">{selected.created_at?.slice(0, 10) || "—"}</p>
                  </div>
                  {selected.converted_at && (
                    <div className="text-sm">
                      <p className="font-medium">Converted to client</p>
                      <p className="text-xs text-muted-foreground">{selected.converted_at?.slice(0, 10)}</p>
                    </div>
                  )}
                </div>
              </div>
            </>
          )}
        </SheetContent>
      </Sheet>
    </div>
  );
}
